name: Crear discusión con resumen de commits

on:
  workflow_dispatch:

jobs:
  crear-discusion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Obtener últimos 5 commits y guardar en Markdown
        run: |
          echo "# Resumen de commits recientes" > resumen.md
          echo "" >> resumen.md
          git log -n 5 --pretty=format:"- %h %s (%an, %ad)" --date=short >> resumen.md

      - name: Leer archivo Markdown y guardar contenido
        id: leer_md
        run: |
          BODY=$(cat resumen.md | jq -Rs .)
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: Crear discusión en GitHub
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ GITHUB_REPOSITORY }}/discussions \
            -d @- <<EOF
          {
            "title": "Resumen automático de commits - $(date +'%Y-%m-%d')",
            "body": ${{ steps.leer_md.outputs.body }},
            "category_id": "${{ secrets.DISCUSSION_CATEGORY_ID }}"
          }
